### ISSUE TITLE
Bugs #2

### ISSUE THREAD

**Issue by Denchan-san** [GEOFARL/bid-for-good#11]
1. Create user 
     1.1 Email validation needed
![image](https://github.com/GEOFARL/bid-for-good/assets/119429548/505231f3-8bfb-429c-9d0a-a9c28d94527d)

2. Login user
     2.1 Email login validation needed
![image](https://github.com/GEOFARL/bid-for-good/assets/119429548/9993942c-251b-42bd-817b-dc56dbad74ed)

3. Create bet
     3.1 Value of bet can't be double-type
![image](https://github.com/GEOFARL/bid-for-good/assets/119429548/25d1373c-a4d7-4e36-aa17-9e26614e9f22)

4. Get auction users
     4.1 if auctionId does not exist : [] (returns nothing)
![image](https://github.com/GEOFARL/bid-for-good/assets/119429548/ac15a9b5-8e2e-488a-94f0-b8c6bd0488ec)

5. Create auction photo 
      5.1 "invalid signature" even if format of file is normal
![image](https://github.com/GEOFARL/bid-for-good/assets/119429548/3e973105-21ab-497e-941f-f84d86c51807)

6. Upload auction photo 
      6.1 doesn't work due previous bug

7. Update auction photo 
      7.1 doesn't work due previous bug

9. Get auction photo 
      8.1 doesn't work due previous bug

**Comment by GEOFARL** [comment]
Great Job! Do not stop, believe in yourself, everything is possible
